"""
Compiled Kobra program

AUTO-GENERATED by kobra/emitter_py.py -- do not edit by hand.
Source: DjinnOS_Shyagzun/shygazun/sanctum/charters/tile_atlas.ko

Kobra Seth: all  Scope: all  Lo: all
"""
from __future__ import annotations
import dataclasses


class KobraSuccess:
    """Kobra success carrier (KaelShi)."""
    def __init__(self, value):
        self.value = value
    def __bool__(self) -> bool:
        return True


class KobraError(Exception):
    """Kobra error carrier (KaelKe)."""


def kysha(*branches):
    """Kysha gate: all branches must be non-None."""
    if not all(b is not None for b in branches):
        raise KobraError("kysha gate failed")
    return branches


def kyra(value):
    """Kyra: identity / control token pass-through."""
    return value



# ── Lo: SethTileAtlas::TileAtlas-1-6::LoGaoh ────────────────────────

# meta: MavoAtlasSpec
sa_wu_ung = "MavoSaWuUng"  # WuUng register: SamosGaoh
sao_wu_ung = "MavoSaoWuUng"  # WuUng register: SamosAo
syr_wu_ung = "MavoSyrWuUng"  # WuUng register: SamosYe
seth_wu_ung = "MavoSethWuUng"  # WuUng register: SamosUi
samos_wu_ung = "MavoSamosWuUng"  # WuUng register: SamosShu
sava_wu_ung = "MavoSavaWuUng"  # WuUng register: SamosKiel
sael_wu_ung = "MavoSaelWuUng"  # WuUng register: SamosYeshu
mek_wu_ung = "MavoMekWuUng"  # WuUng register: SamosLao
myrun_wu_ung = "MavoMyrunWuUng"  # WuUng register: SamosShushy

# ── Lo: SethTileAtlas::TileAtlas-1-6::LoAo ──────────────────────────

@dataclasses.dataclass
class AtlasDecl:
    """AtlasDecl — base atlas object (Sao: persistent, Ep: versioned)."""
    kind:    str = "MavoAtlasDecl"
    version: int = 0

@dataclasses.dataclass
class TileFileDecl(AtlasDecl):
    """TileFileDecl — a single tile file (Sao = persistent object)."""
    path:       str   = ""
    width:      int   = 0
    height:     int   = 0
    pixel_data: bytes = b""
    tongue_eq:  str   = "MavoSaoWuUng"

@dataclasses.dataclass
class TileDirDecl(AtlasDecl):
    """TileDirDecl — a directory of tile files (Seth = bundle)."""
    path:      str  = ""
    files:     list = dataclasses.field(default_factory=list)
    tongue_eq: str  = "MavoSethWuUng"

@dataclasses.dataclass
class AtlasClusterDecl(AtlasDecl):
    """AtlasClusterDecl — cluster of tile directories (Samos = database cluster)."""
    cluster_id: int  = 0
    dirs:       list = dataclasses.field(default_factory=list)
    tongue_eq:  str  = "MavoSamosWuUng"

@dataclasses.dataclass
class AtlasVAddrDecl(AtlasDecl):
    """AtlasVAddrDecl — virtual address into the atlas texture (Sa = root volume)."""
    base_offset: int = 0
    sheet_x:     int = 0
    sheet_y:     int = 0
    tile_w:      int = 0
    tile_h:      int = 0
    tongue_eq:   str = "MavoSaWuUng"

def atlas_read_eval(tile_file: "TileFileDecl",
                    tile_dir:  "TileDirDecl",
                    cluster:   "AtlasClusterDecl") -> bool:
    """AtlasReadEval — Kysha gate: validate file in dir, dir in cluster."""
    dir_file_paths = [f.path for f in tile_dir.files]
    if tile_file.path and tile_file.path not in dir_file_paths:
        raise KobraError(
            f"atlas_read_eval: {tile_file.path!r} not in dir {tile_dir.path!r}")
    cluster_dir_paths = [d.path for d in cluster.dirs]
    if tile_dir.path and tile_dir.path not in cluster_dir_paths:
        raise KobraError(
            f"atlas_read_eval: dir {tile_dir.path!r} not in cluster {cluster.cluster_id}")
    return True

def atlas_index_el(tile_dir:  "TileDirDecl",
                   tile_file: "TileFileDecl",
                   cluster:   "AtlasClusterDecl") -> "AtlasVAddrDecl":
    """AtlasIndexEl — compute atlas virtual address (sheet_x, sheet_y) for a tile."""
    file_paths = [f.path for f in tile_dir.files]
    fi   = file_paths.index(tile_file.path) if tile_file.path in file_paths else 0
    cols = max(1, int(len(tile_dir.files) ** 0.5))
    dir_paths = [d.path for d in cluster.dirs]
    di = dir_paths.index(tile_dir.path) if tile_dir.path in dir_paths else 0
    return AtlasVAddrDecl(
        base_offset=di * len(tile_dir.files) + fi,
        sheet_x=fi % cols,
        sheet_y=fi // cols,
        tile_w=tile_file.width,
        tile_h=tile_file.height,
    )


# ── Lo: SethTileAtlas::TileAtlas-1-6::LoYe ──────────────────────────

def atlas_backing(tile_file: "TileFileDecl",
                  tile_dir:  "TileDirDecl") -> bytearray:
    """AtlasBacking — load tile pixel data into a RAM bytearray (OceanusDecl backing)."""
    buf = bytearray()
    for f in tile_dir.files:
        buf.extend(f.pixel_data or bytes(max(1, f.width) * max(1, f.height) * 4))
    return buf

def atlas_page_el(tile_file: "TileFileDecl") -> bytes:
    """AtlasPageEl — return a tile's pixel data, loading from disk if absent."""
    if tile_file.pixel_data:
        return tile_file.pixel_data
    try:
        with open(tile_file.path, "rb") as fh:
            return fh.read()
    except OSError:
        return bytes(max(1, tile_file.width) * max(1, tile_file.height) * 4)


# ── Lo: SethTileAtlas::TileAtlas-1-6::LoUi ──────────────────────────

@dataclasses.dataclass
class AtlasCacheDecl(AtlasDecl):
    """AtlasCacheDecl — hot LRU page cache (Sael = leftovers/cache)."""
    max_pages: int  = 64
    pages:     dict = dataclasses.field(default_factory=dict)
    tongue_eq: str  = "MavoSaelWuUng"

    def is_hot(self, path: str) -> bool:
        return path in self.pages

    def promote(self, path: str, data: bytes) -> None:
        if path not in self.pages and len(self.pages) >= self.max_pages:
            evict_key = next(iter(self.pages))
            del self.pages[evict_key]
        self.pages[path] = data

    def evict(self, path: str) -> None:
        self.pages.pop(path, None)

def hot_page_eval(cache:     "AtlasCacheDecl",
                  tile_file: "TileFileDecl") -> bool:
    """HotPageEval — Kysha gate: true if tile is in the MnemosyneDecl hot cache."""
    return cache.is_hot(tile_file.path)

def hot_page_el(cache:     "AtlasCacheDecl",
                tile_file: "TileFileDecl") -> "AtlasCacheDecl":
    """HotPageEl — promote a tile page into the LRU hot cache."""
    cache.promote(tile_file.path, atlas_page_el(tile_file))
    return cache

def page_evict_el(cache:     "AtlasCacheDecl",
                  tile_file: "TileFileDecl") -> "AtlasCacheDecl":
    """PageEvictEl — evict a tile from the hot cache back to RAM backing."""
    cache.evict(tile_file.path)
    return cache


# ── Lo: SethTileAtlas::TileAtlas-1-6::LoShu ─────────────────────────

@dataclasses.dataclass
class AtlasSnapshotDecl(AtlasDecl):
    """AtlasSnapshotDecl — snapshot manifest of atlas state (Sava = archive)."""
    manifest:  dict = dataclasses.field(default_factory=dict)
    tongue_eq: str  = "MavoSavaWuUng"

def atlas_bus_eval(vaddr:   "AtlasVAddrDecl",
                   cluster: "AtlasClusterDecl") -> bool:
    """AtlasBusEval — Kysha gate: vaddr within cluster bounds (GygesDecl bus)."""
    total_tiles = sum(len(d.files) for d in cluster.dirs)
    if vaddr.base_offset < 0 or (total_tiles > 0 and vaddr.base_offset >= total_tiles):
        raise KobraError(
            f"atlas_bus_eval: vaddr {vaddr.base_offset} out of bounds "
            f"(cluster has {total_tiles} tiles)")
    return True

def atlas_dma_el(vaddr:   "AtlasVAddrDecl",
                 backing: bytearray) -> dict:
    """AtlasDMAEl — DMA transfer descriptor for the tile at vaddr."""
    tile_bytes = vaddr.tile_w * vaddr.tile_h * 4
    offset     = vaddr.base_offset * tile_bytes
    return {
        "offset":    offset,
        "length":    tile_bytes,
        "sheet_x":   vaddr.sheet_x,
        "sheet_y":   vaddr.sheet_y,
        "tile_w":    vaddr.tile_w,
        "tile_h":    vaddr.tile_h,
        "data_view": bytes(backing[offset:offset + tile_bytes]),
    }

def atlas_stream_el(snapshot: "AtlasSnapshotDecl",
                    cluster:  "AtlasClusterDecl") -> list:
    """AtlasStreamEl — stream-load tiles listed in the snapshot manifest."""
    transfers = []
    for path, vaddr in snapshot.manifest.items():
        data = atlas_page_el(TileFileDecl(path=path))
        transfers.append({"path": path, "vaddr": vaddr, "data": data})
    return transfers


# ── Lo: SethTileAtlas::TileAtlas-1-6::LoLao ─────────────────────────

def atlas_render_eval(cluster:  "AtlasClusterDecl",
                      cache:    "AtlasCacheDecl",
                      snapshot: "AtlasSnapshotDecl") -> dict:
    """AtlasRenderEval — full atlas pipeline.

    Ouranos  — virtual address table (vaddr per tile)
    Oceanus  — RAM backing bytearray
    Mnemosyne— hot LRU page cache
    Gyges    — DMA transfer descriptors (wide bus)
    Theia    — GPU atlas sheet descriptor (output)
    """
    all_files = [f for d in cluster.dirs for f in d.files]
    if not all_files:
        return {"width": 0, "height": 0, "data": b"", "vaddrs": {}}

    tile_w = max((f.width  for f in all_files), default=0)
    tile_h = max((f.height for f in all_files), default=0)
    if tile_w == 0 or tile_h == 0:
        return {"width": 0, "height": 0, "data": b"", "vaddrs": {}}

    cols    = max(1, int(len(all_files) ** 0.5))
    rows    = (len(all_files) + cols - 1) // cols
    sheet_w = cols * tile_w
    sheet_h = rows * tile_h
    sheet   = bytearray(sheet_w * sheet_h * 4)
    vaddrs: dict = {}

    for idx, tf in enumerate(all_files):
        sx   = (idx % cols) * tile_w
        sy   = (idx // cols) * tile_h
        data = cache.pages.get(tf.path) or atlas_page_el(tf)
        tile_row_bytes = tile_w * 4
        for row in range(tile_h):
            src_off = row * tile_row_bytes
            dst_off = ((sy + row) * sheet_w + sx) * 4
            chunk   = data[src_off:src_off + tile_row_bytes]
            sheet[dst_off:dst_off + len(chunk)] = chunk
        vaddrs[tf.path] = AtlasVAddrDecl(
            base_offset=idx, sheet_x=sx, sheet_y=sy, tile_w=tile_w, tile_h=tile_h)

    return {
        "width":  sheet_w,
        "height": sheet_h,
        "data":   bytes(sheet),
        "vaddrs": vaddrs,
    }

def atlas_shi_wu_ung(atlas_result: dict) -> "KobraSuccess":
    """AtlasShiWuUng — KaelShi: emit atlas sheet on success."""
    return KobraSuccess(atlas_result)

def atlas_ke_wu_ung(reason: str = "") -> None:
    """AtlasKeWuUng — KaelKe: raise KobraError on atlas failure."""
    raise KobraError(f"atlas pipeline failed: {reason}")

def atlas_ep_em(cluster:  "AtlasClusterDecl",
                cache:    "AtlasCacheDecl",
                snapshot: "AtlasSnapshotDecl") -> dict:
    """AtlasEpEm — combined atlas pipeline: success or error branch."""
    try:
        result = atlas_render_eval(cluster, cache, snapshot)
        return atlas_shi_wu_ung(result).value
    except KobraError:
        raise
    except Exception as exc:
        atlas_ke_wu_ung(str(exc))
        return {}

