"""
ambroflow/kobra_compiled/bok_engine.py
=======================================
Compiled Kobra BoK/Julia engine.

AUTO-GENERATED by kobra/emitter_py.py from:
    selfspec.ko  SethKernel :: YeGaoh-1-8 :: LoLao    (BreathOfKo mathematics)
    selfspec.ko  SethKernel :: YeGaoh-1-8 :: LoYeshu  (Julia topology)

Source Kobra words emitted here
--------------------------------
  MavoAzothLo          → azoth_lo()            base accumulation loop
  MavoMobiusCoil       → mobius_coil()          Gaoh c-parameter (Möbius coil)
  MavoCoilEp           → coil_ep()              advance coil one game
  MavoJuliaFaUng       → julia_fa_ung()         smooth Julia iteration (one pixel)
  MavoJuliaFaFy        → julia_fa_fy()          full Julia grid accumulation
  MavoAzothShak        → azoth_shak()           Shak-tinted Azoth variant
  MavoAzothMobiusFoa   → azoth_mobius_foa()     Möbius-folded Azoth
  MavoAzothSuFoa       → azoth_su_foa()         Su-folded Azoth (iteration count)
  MavoShiBi            → shi_bi()               convergence mode: bounded
  MavoKeShiBi          → ke_shi_bi()            convergence mode: ke-shi (edge)
  MavoShiKeBi          → shi_ke_bi()            convergence mode: shi-ke (error)
  MavoKoFoaShiKeWuUng  → ko_foa_shi_ke_wu_ung() Ko's fork: Kaganue vs Drovitth
  MavoPufFyLoVaShy     → PufFyLoVaShy           BoK state variable class
  MavoPufFyLoShak      → puf_fy_lo_shak()       BoK snapshot update
  MavoPufFyLoShiWuUng  → puf_fy_lo_shi_wu_ung() success emission (KaelShi)
  MavoPufFyLoKeWuUng   → puf_fy_lo_ke_wu_ung()  error emission (KaelKe)
  MavoPufFyLoEpEm      → puf_fy_lo_ep_em()      combined branch

Compatibility
-------------
All functions are interface-compatible with ambroflow.ko.breath.BreathOfKo:
  azoth_lo()           matches _derive_azoth()
  mobius_coil()        matches _gaoh_constant()
  julia_fa_ung()       matches _mandelbrot_smooth() (from ko/render.py)
  PufFyLoVaShy.azoth() matches BreathOfKo.azoth()
  PufFyLoVaShy.gaoh_c() matches BreathOfKo.gaoh_constant()

The compiled engine exercises the full hw.ko pipeline:
  OceanusDecl (RAM) → CoeusDecl (CPU) → TheiaDecl (GPU/display output)
mapped in Python as: julia grid → iteration computation → snapshot dict.
"""
from __future__ import annotations

import math
import statistics
from typing import Any


# ── Runtime error type ────────────────────────────────────────────────────────

class KobraError(Exception):
    """KaelKe cluster error: raised by error-branch words (PufFyLoKeWuUng etc.)."""
    pass


# ── WuUng register identifiers (compiled from LoAoHa WuUng declarations) ──────

LOTUS_WU_UNG     = "MavoLotusWuUng"       # T1  — Ao
ROSE_WU_UNG      = "MavoRoseWuUng"        # T2  — Ye
SAKURA_WU_UNG    = "MavoSakuraWuUng"      # T3  — Ui
FOLD_WU_UNG      = "MavoFoldWuUng"        # T25 — YeAo
TOPOLOGY_WU_UNG  = "MavoTopologyWuUng"    # T26 — YeYe
PHASE_WU_UNG     = "MavoPhaseWuUng"       # T27 — YeUi
GRADIENT_WU_UNG  = "MavoGradientWuUng"    # T28 — YeShu
CURVATURE_WU_UNG = "MavoCurvatureWuUng"   # T29 — YeKiel


# ── AzothLo — base accumulation loop ─────────────────────────────────────────
# Kobra: [MavoAzothLo MavoSamos MavoEp MavoSy MavoKael MavoGaohNaAERuKi MavoWuUng]
# Maps to: _derive_azoth() in ambroflow.ko.breath

def azoth_lo(
    layer_densities: dict[int, float],
    coil_position:   float,
    flag_weight:     float = 0.0,
) -> complex:
    """AzothLo — derives the Azoth complex number from 24 layer densities.

    Lotus layers (1–8):  material ground → real axis
    Rose layers (9–16):  relational state → imaginary axis
    Sakura layers (17–24): orientation scale factor applied to both axes
    Flag weight: adds a bounded spiral contribution.
    """
    lotus_vals  = [layer_densities.get(i, 0.5) for i in range(1,  9)]
    rose_vals   = [layer_densities.get(i, 0.5) for i in range(9,  17)]
    sakura_vals = [layer_densities.get(i, 0.5) for i in range(17, 25)]

    lotus_mean  = statistics.mean(lotus_vals)
    rose_mean   = statistics.mean(rose_vals)
    sakura_mean = statistics.mean(sakura_vals)

    real   = lotus_mean  * sakura_mean * 4.0 - 2.0
    imag   = rose_mean   * sakura_mean * 4.0 - 2.0
    spiral = flag_weight * 0.05
    return complex(real + spiral, imag + spiral)


# ── MobiusCoil — Gaoh c-parameter ────────────────────────────────────────────
# Kobra: [MavoMobiusCoil MavoAzothLo MavoAonkiel Ha MavoWuUng MavoSy MavoKael MavoSao]
# Maps to: _gaoh_constant() in ambroflow.ko.breath

def mobius_coil(coil_position: float) -> complex:
    """MobiusCoil — Möbius coil constant: Gaoh as Julia c-parameter.

    Real part:      31/255 ≈ 0.122  (Gaoh = 31, normalized)
    Imaginary part: sin(θ) × 0.1   (encodes coil position as Möbius fold)
    At coil 0 and 12 (the Möbius pair): imaginary = 0.
    """
    real  = 31 / 255.0
    theta = (coil_position / 12.0) * 2 * math.pi
    imag  = math.sin(theta) * 0.1
    return complex(real, imag)


# ── CoilEp — advance the coil ────────────────────────────────────────────────
# Kobra: [MavoCoilEp MavoMobiusCoil MavoGaoh MavoAonkiel Ha MavoLoAo Kyra MavoMekha MavoSao]

def coil_ep(coil_position: float, n_games: int = 31) -> float:
    """CoilEp — advance coil position by one game increment.

    The Möbius coil completes one full rotation across all 31 games.
    """
    return (coil_position + 12.0 / n_games) % 12.0


# ── JuliaFaUng — smooth iteration for one complex point ──────────────────────
# Kobra: [MavoJuliaFaUng MavoShiKaKoKiEl MavoLoAo Kyra ... MavoSava MavoKael]
# Maps to: _mandelbrot_smooth() in ambroflow.ko.render

_MAX_ITER_JULIA = 512


def julia_fa_ung(z0: complex, c: complex, max_iter: int = _MAX_ITER_JULIA) -> float:
    """JuliaFaUng — smooth Julia-set iteration count for starting point z₀.

    Uses the standard smooth escape-time algorithm:
        smooth_i = i + 1 - log₂(log₂(|z|))
    Returns float(max_iter) for bounded (interior) points.
    """
    z = z0
    for i in range(max_iter):
        if abs(z) > 2.0:
            log_zn = math.log(abs(z))
            nu     = math.log(log_zn / math.log(2)) / math.log(2)
            return float(i) + 1.0 - nu
        z = z * z + c
    return float(max_iter)


# ── JuliaFaFy — full Julia grid accumulation ─────────────────────────────────
# Kobra: [MavoJuliaFaFy MavoJuliaFaUng MavoOs MavoIer MavoShiKaKoKiEl Kyra Kysha ...]
# Maps to: _mandelbrot_smooth grid loop in ambroflow.ko.render

def julia_fa_fy(
    c:        complex,
    size:     int   = 512,
    half:     float = 1.8,
    max_iter: int   = _MAX_ITER_JULIA,
) -> list[list[float]]:
    """JuliaFaFy — accumulate full Julia-set grid of smooth iteration counts.

    The grid covers [-half, half] × [-half, half] in the complex plane.
    Returns a size×size list of smooth iteration counts.
    """
    x_min, x_max = -half, half
    y_min, y_max = -half, half
    grid: list[list[float]] = []
    for row in range(size):
        im   = y_min + (y_max - y_min) * row / size
        line: list[float] = []
        for col in range(size):
            re = x_min + (x_max - x_min) * col / size
            line.append(julia_fa_ung(complex(re, im), c, max_iter))
        grid.append(line)
    return grid


# ── AzothShak — Shak-tinted Azoth variant ────────────────────────────────────
# Kobra: [MavoAzothShak MavoAzothLo MavoYeGaohLo ...]

def azoth_shak(
    layer_densities: dict[int, float],
    coil_position:   float,
    flag_weight:     float = 0.0,
) -> complex:
    """AzothShak — Wunashakoun-tinted Azoth: slight imaginary bias toward boundary."""
    base = azoth_lo(layer_densities, coil_position, flag_weight)
    return complex(base.real * 0.98, base.imag + 0.012)


# ── AzothMobiusFoa — Möbius-folded Azoth ─────────────────────────────────────
# Kobra: [MavoAzothMobiusFoa MavoAzothShak MavoGaohNaAERuKi MavoHa MavoSy ...]

def azoth_mobius_foa(
    layer_densities: dict[int, float],
    coil_position:   float,
    flag_weight:     float = 0.0,
) -> complex:
    """AzothMobiusFoa — Möbius-folded Azoth: rotate by coil's imaginary phase."""
    base  = azoth_shak(layer_densities, coil_position, flag_weight)
    c     = mobius_coil(coil_position)
    theta = math.atan2(base.imag, base.real)
    r     = abs(base)
    fold  = complex(
        r * math.cos(theta + c.imag),
        r * math.sin(theta + c.imag),
    )
    return fold


# ── AzothSuFoa — Su-folded Azoth (iteration count) ───────────────────────────
# Kobra: [MavoAzothSuFoa MavoAzothMobiusFoa MavoAo MavoUinshu MavoShu MavoUi ...]

def azoth_su_foa(
    layer_densities: dict[int, float],
    coil_position:   float,
    flag_weight:     float = 0.0,
) -> int:
    """AzothSuFoa — iteration count at the player's Möbius-folded Azoth position."""
    z0 = azoth_mobius_foa(layer_densities, coil_position, flag_weight)
    c  = mobius_coil(coil_position)
    return int(julia_fa_ung(z0, c))


# ── Convergence modes (ShiBi / KeShiBi / ShiKeBi) ────────────────────────────
# Kobra: [MavoShiBi ...] [MavoKeShiBi ...] [MavoShiKeBi ...]

def shi_bi(iteration_count: int, max_iter: int = _MAX_ITER_JULIA) -> str:
    """ShiBi — primary convergence: bounded → 'bounded', else 'edge'."""
    return "bounded" if iteration_count >= max_iter else "edge"


def ke_shi_bi(iteration_count: int, max_iter: int = _MAX_ITER_JULIA) -> str:
    """KeShiBi — ke-shi convergence: near-boundary (FyShy gate)."""
    return "edge" if iteration_count >= max_iter // 2 else "unbounded"


def shi_ke_bi(iteration_count: int, max_iter: int = _MAX_ITER_JULIA) -> str:
    """ShiKeBi — shi-ke convergence: error/unbounded check."""
    return "unbounded" if iteration_count < max_iter // 2 else "edge"


# ── KoFoaShiKeWuUng — Ko's fork ──────────────────────────────────────────────
# Kobra: [MavoKoFoaShiKeWuUng MavoAzothSuFoa MavoYe MavoSymbolEq Kyra
#          MavoKaelKokielUng MavoKaganue MavoDrovitth Kysha MavoSao]

def ko_foa_shi_ke_wu_ung(iteration_count: int, max_iter: int = _MAX_ITER_JULIA) -> str:
    """KoFoaShiKeWuUng — Ko's fork selection.

    Kaganue path: bounded integration (iteration_count >= max_iter)
    Drovitth path: living inquiry (edge — near boundary)
    Default (unbounded): routes to Kaganue (integration path remains open).
    """
    if iteration_count >= max_iter:
        return "Kaganue"     # complete integration — KaelKokielUng full
    elif iteration_count >= max_iter // 2:
        return "Drovitth"    # edge — living philosophical inquiry
    else:
        return "Kaganue"     # unbounded still routes to integration path


# ── PufFyLoVaShy — BoK state variable class ──────────────────────────────────
# Kobra: [MavoPufFyLoVaShy MavoAzothLo MavoMobiusCoil MavoCoilEp ... MavoMavo]

class PufFyLoVaShy:
    """PufFyLoVaShy — BreathOfKo state variable (compiled Kobra form).

    Holds the full Azoth+coil+density state.  Method names map to
    their ambroflow.ko.breath.BreathOfKo equivalents for test compatibility.
    """

    def __init__(
        self,
        layer_densities: dict[int, float] | None = None,
        coil_position:   float = 6.0,
        flag_weight:     float = 0.0,
        games_played:    int   = 0,
    ) -> None:
        self.layer_densities: dict[int, float] = (
            layer_densities if layer_densities is not None
            else {i: 0.5 for i in range(1, 25)}
        )
        self.coil_position = coil_position
        self.flag_weight   = flag_weight
        self.games_played  = games_played

    # Interface compatibility with BreathOfKo

    def azoth(self) -> complex:
        """Azoth complex number — matches BreathOfKo.azoth()."""
        return azoth_lo(self.layer_densities, self.coil_position, self.flag_weight)

    def gaoh_constant(self) -> complex:
        """Gaoh constant — matches BreathOfKo.gaoh_constant()."""
        return mobius_coil(self.coil_position)

    def boundedness(self) -> str:
        """Boundedness string — matches BreathOfKo.boundedness()."""
        it = azoth_su_foa(self.layer_densities, self.coil_position, self.flag_weight)
        if it >= _MAX_ITER_JULIA:
            return "bounded"
        elif it >= _MAX_ITER_JULIA // 2:
            return "edge"
        return "unbounded"

    def ko_path(self) -> str:
        """Ko's path selection: Kaganue or Drovitth."""
        it = azoth_su_foa(self.layer_densities, self.coil_position, self.flag_weight)
        return ko_foa_shi_ke_wu_ung(it)

    def snapshot(self) -> dict:
        """Snapshot dict — interface-compatible with BreathOfKo.snapshot()."""
        az = self.azoth()
        return {
            "layer_densities": dict(self.layer_densities),
            "coil_position":   self.coil_position,
            "games_played":    self.games_played,
            "azoth":           [az.real, az.imag],
            "boundedness":     self.boundedness(),
            "ko_path":         self.ko_path(),
        }

    def __repr__(self) -> str:
        return (
            f"PufFyLoVaShy(coil={self.coil_position:.3f}, "
            f"games={self.games_played}, "
            f"boundedness={self.boundedness()!r})"
        )


# ── PufFyLoShak — BoK snapshot update ────────────────────────────────────────
# Kobra: [MavoPufFyLoShak MavoPufFyLoVaShy MavoGaohNaAERuKi MavoWu ... MavoGwev MavoSava]

def puf_fy_lo_shak(
    state:               "PufFyLoVaShy",
    calibration_density: float,
) -> "PufFyLoVaShy":
    """PufFyLoShak — integrate one calibration pass into the BoK state.

    Updates all 24 layer densities as a rolling average, then advances
    the coil position by one game increment.
    """
    n             = state.games_played + 1
    new_densities = {}
    for idx, current in state.layer_densities.items():
        new_densities[idx] = round((current * (n - 1) + calibration_density) / n, 4)
    return PufFyLoVaShy(
        layer_densities = new_densities,
        coil_position   = coil_ep(state.coil_position),
        flag_weight     = state.flag_weight,
        games_played    = n,
    )


# ── PufFyLoShiWuUng — success emission (KaelShi) ─────────────────────────────
# Kobra: [MavoPufFyLoShiWuUng MavoPufFyLoVaShy KaelShi ... Kysha KaelShi]

def puf_fy_lo_shi_wu_ung(state: "PufFyLoVaShy") -> dict:
    """PufFyLoShiWuUng — KaelShi: emit the full BoK snapshot (success branch)."""
    return state.snapshot()


# ── PufFyLoKeWuUng — error emission (KaelKe) ─────────────────────────────────
# Kobra: [MavoPufFyLoKeWuUng MavoPufFyLoVaShy MavoKeWuUng Kysha KaelKe]

def puf_fy_lo_ke_wu_ung(state: "PufFyLoVaShy", reason: str = "") -> None:
    """PufFyLoKeWuUng — KaelKe: raise on BoK emission failure (error branch)."""
    msg = reason or f"BoK emission failed: boundedness={state.boundedness()!r}"
    raise KobraError(msg)


# ── PufFyLoEpEm — combined emission branch ───────────────────────────────────
# Kobra: [MavoPufFyLoEpEm MavoPufFyLoShiWuUng Kyra MavoPufFyLoKeWuUng Kyra Kysha]

def puf_fy_lo_ep_em(state: "PufFyLoVaShy") -> dict:
    """PufFyLoEpEm — combined success/error emission (Kysha gate)."""
    try:
        return puf_fy_lo_shi_wu_ung(state)
    except Exception as exc:
        try:
            puf_fy_lo_ke_wu_ung(state, str(exc))
        except Exception:
            pass
        return {}


