"""
Compiled Kobra program

AUTO-GENERATED by kobra/emitter_py.py -- do not edit by hand.
Source: DjinnOS_Shyagzun/shygazun/sanctum/charters/tile_mesh.ko

Kobra Seth: all  Scope: all  Lo: all
"""
from __future__ import annotations
import dataclasses


class KobraSuccess:
    """Kobra success carrier (KaelShi)."""
    def __init__(self, value):
        self.value = value
    def __bool__(self) -> bool:
        return True


class KobraError(Exception):
    """Kobra error carrier (KaelKe)."""


def kysha(*branches):
    """Kysha gate: all branches must be non-None."""
    if not all(b is not None for b in branches):
        raise KobraError("kysha gate failed")
    return branches


def kyra(value):
    """Kyra: identity / control token pass-through."""
    return value



# ── Lo: SethTileMesh::TileMesh-1-5::LoGaoh ──────────────────────────

# meta: MavoMeshSpec
jy_wu_ung = "MavoJyWuUng"  # WuUng register: FoldGaoh
ji_wu_ung = "MavoJiWuUng"  # WuUng register: FoldAo
ja_wu_ung = "MavoJaWuUng"  # WuUng register: FoldYe
jo_wu_ung = "MavoJoWuUng"  # WuUng register: FoldUi
je_wu_ung = "MavoJeWuUng"  # WuUng register: FoldShu
ju_wu_ung = "MavoJuWuUng"  # WuUng register: FoldKiel
vertex_wu_ung = "MavoVertexWuUng"  # WuUng register: FoldYeshu
face_wu_ung = "MavoFaceWuUng"  # WuUng register: FoldLao
batch_wu_ung = "MavoBatchWuUng"  # WuUng register: FoldShushy

# ── Lo: SethTileMesh::TileMesh-1-5::LoAo ────────────────────────────

@dataclasses.dataclass
class MeshDecl:
    """MeshDecl — base mesh object."""
    kind:    str = "MavoMeshDecl"
    version: int = 0

@dataclasses.dataclass
class MeshVertexDecl(MeshDecl):
    """MeshVertexDecl — 3D vertex: position, normal, UV (VertexWuUng)."""
    position:  tuple = (0.0, 0.0, 0.0)
    normal:    tuple = (0.0, 1.0, 0.0)
    uv:        tuple = (0.0, 0.0)
    tongue_eq: str   = "MavoVertexWuUng"

@dataclasses.dataclass
class MeshFaceDecl(MeshDecl):
    """MeshFaceDecl — triangle face: vertex indices + Sakura orientation (FaceWuUng)."""
    vertex_indices: list = dataclasses.field(default_factory=list)
    orient_dir:     str  = "MavoJyWuUng"
    atlas_tile:     str  = ""
    tongue_eq:      str  = "MavoFaceWuUng"

@dataclasses.dataclass
class MeshBatchDecl(MeshDecl):
    """MeshBatchDecl — render batch: ordered face list for instanced draw (BatchWuUng)."""
    faces:     list = dataclasses.field(default_factory=list)
    batch_id:  int  = 0
    tongue_eq: str  = "MavoBatchWuUng"

def mesh_read_eval(vertices: list,
                   faces:    list,
                   batches:  list) -> bool:
    """MeshReadEval — Kysha gate: validate mesh index integrity."""
    n_verts = len(vertices)
    for face in faces:
        for idx in face.vertex_indices:
            if idx < 0 or idx >= n_verts:
                raise KobraError(
                    f"mesh_read_eval: face index {idx} out of range (n_verts={n_verts})")
    return True

def mesh_index_el(face:  "MeshFaceDecl",
                  batch: "MeshBatchDecl") -> int:
    """MeshIndexEl — append face to batch and return its slot index."""
    batch.faces.append(face)
    return len(batch.faces) - 1


# ── Lo: SethTileMesh::TileMesh-1-5::LoYe ────────────────────────────

def mesh_buffer_eval(vertices: list,
                     faces:    list) -> bytearray:
    """MeshBufferEval — pack vertices into an interleaved VBO bytearray (OceanusDecl).

    Stride = 44 bytes per vertex:
        position  3×f32  (12 B)
        normal    3×f32  (12 B)
        uv        2×f32  ( 8 B)
        pad       3×f32  (12 B — reserved: tangent x/y/z)
    """
    import struct
    STRIDE = 44
    buf = bytearray(len(vertices) * STRIDE)
    for i, v in enumerate(vertices):
        pos = v.position if len(v.position) == 3 else (0.0, 0.0, 0.0)
        nrm = v.normal   if len(v.normal)   == 3 else (0.0, 1.0, 0.0)
        uv  = v.uv       if len(v.uv)       == 2 else (0.0, 0.0)
        struct.pack_into("<8f", buf, i * STRIDE,
                         pos[0], pos[1], pos[2],
                         nrm[0], nrm[1], nrm[2],
                         uv[0],  uv[1])
    return buf

def vertex_buffer_el(vertices: list) -> dict:
    """VertexBufferEl — create a VBO descriptor ready for GL upload."""
    return {
        "vertex_count": len(vertices),
        "stride":       44,
        "data":         mesh_buffer_eval(vertices, []),
    }


# ── Lo: SethTileMesh::TileMesh-1-5::LoUi ────────────────────────────

# Sakura face-direction constants (bytes 48-53) -> unit normal vectors
FACE_NORMALS: dict = {
    "MavoJyWuUng": ( 0.0,  1.0,  0.0),   # Jy — Top      (+Y)
    "MavoJiWuUng": ( 1.0,  0.0,  0.0),   # Ji — Starboard (+X)
    "MavoJaWuUng": ( 0.0,  0.0,  1.0),   # Ja — Front     (+Z)
    "MavoJoWuUng": ( 0.0,  0.0, -1.0),   # Jo — Back      (-Z)
    "MavoJeWuUng": (-1.0,  0.0,  0.0),   # Je — Port      (-X)
    "MavoJuWuUng": ( 0.0, -1.0,  0.0),   # Ju — Bottom    (-Y)
}

@dataclasses.dataclass
class FaceOrientDecl(MeshDecl):
    """FaceOrientDecl — face orientation classifier (Jy = Top/+Y default)."""
    direction:  str = "MavoJyWuUng"
    tongue_eq:  str = "MavoJyWuUng"

    @property
    def normal(self) -> tuple:
        return FACE_NORMALS.get(self.direction, (0.0, 1.0, 0.0))

def face_orient_eval(face: "MeshFaceDecl") -> dict:
    """FaceOrientEval — Kysha gate: resolve all 6 Sakura directions for a face."""
    orient = FaceOrientDecl(direction=face.orient_dir)
    return {
        "normal":   orient.normal,
        "all_dirs": dict(FACE_NORMALS),
        "face_dir": face.orient_dir,
    }

def top_face_el(vertex_indices: list,
                atlas_tile:     str = "") -> "MeshFaceDecl":
    """TopFaceEl — construct a face with Top (+Y) orientation (Jy)."""
    return MeshFaceDecl(
        vertex_indices=list(vertex_indices),
        orient_dir="MavoJyWuUng",
        atlas_tile=atlas_tile,
    )

def front_face_el(vertex_indices: list,
                  atlas_tile:     str = "") -> "MeshFaceDecl":
    """FrontFaceEl — construct a face with Front (+Z) orientation (Ja)."""
    return MeshFaceDecl(
        vertex_indices=list(vertex_indices),
        orient_dir="MavoJaWuUng",
        atlas_tile=atlas_tile,
    )


# ── Lo: SethTileMesh::TileMesh-1-5::LoShu ───────────────────────────

@dataclasses.dataclass
class MeshTransformDecl(MeshDecl):
    """MeshTransformDecl — 4×4 column-major transform matrix (BatchWuUng)."""
    matrix:    list = dataclasses.field(
        default_factory=lambda: [
            1.0, 0.0, 0.0, 0.0,
            0.0, 1.0, 0.0, 0.0,
            0.0, 0.0, 1.0, 0.0,
            0.0, 0.0, 0.0, 1.0,
        ]
    )
    tongue_eq: str = "MavoBatchWuUng"

def mesh_transform_eval(batch:     "MeshBatchDecl",
                        transform: "MeshTransformDecl") -> "MeshBatchDecl":
    """MeshTransformEval — apply a 4×4 transform via CoeusDecl (CPU) + GygesDecl (bus).

    Returns a copy of the batch.  The GPU path lives in the GL renderer;
    this CPU path is used for CPU-side culling and physics.
    """
    return MeshBatchDecl(faces=list(batch.faces), batch_id=batch.batch_id)

def mesh_batch_el(batch:     "MeshBatchDecl",
                  transform: "MeshTransformDecl") -> dict:
    """MeshBatchEl — submit a transformed batch to the GygesDecl geometry bus."""
    transformed = mesh_transform_eval(batch, transform)
    index_data  = [idx for face in transformed.faces for idx in face.vertex_indices]
    return {
        "batch_id":   transformed.batch_id,
        "face_count": len(transformed.faces),
        "index_data": index_data,
        "transform":  list(transform.matrix),
    }


# ── Lo: SethTileMesh::TileMesh-1-5::LoLao ───────────────────────────

def mesh_render_eval(vertices:   list,
                     faces:      list,
                     batches:    list,
                     transforms: list | None = None) -> dict:
    """MeshRenderEval — full mesh render pipeline.

    FoldDecl         — 2D→3D winding-order fold from face orientations
    TopologyConnDecl — face→vertex adjacency topology
    OceanusDecl      — RAM vertex buffer
    CoeusDecl        — CPU vertex transform
    GygesDecl        — wide parallel geometry bus
    TheiaDecl        — GPU/display output descriptor
    """
    mesh_read_eval(vertices, faces, batches)
    vbo       = vertex_buffer_el(vertices)
    trs       = transforms or [MeshTransformDecl() for _ in batches]
    submitted = [mesh_batch_el(b, t) for b, t in zip(batches, trs)]
    winding   = {face.orient_dir: FaceOrientDecl(direction=face.orient_dir).normal
                 for face in faces}
    return {
        "vbo":          vbo,
        "batches":      submitted,
        "winding":      winding,
        "face_count":   len(faces),
        "vertex_count": len(vertices),
    }

def mesh_shi_wu_ung(mesh_result: dict) -> "KobraSuccess":
    """MeshShiWuUng — KaelShi: emit mesh render result on success."""
    return KobraSuccess(mesh_result)

def mesh_ke_wu_ung(reason: str = "") -> None:
    """MeshKeWuUng — KaelKe: raise KobraError on mesh failure."""
    raise KobraError(f"mesh pipeline failed: {reason}")

def mesh_ep_em(vertices: list,
               faces:    list,
               batches:  list) -> dict:
    """MeshEpEm — combined mesh pipeline: success or error branch."""
    try:
        result = mesh_render_eval(vertices, faces, batches)
        return mesh_shi_wu_ung(result).value
    except KobraError:
        raise
    except Exception as exc:
        mesh_ke_wu_ung(str(exc))
        return {}

