"""
Compiled Kobra program

AUTO-GENERATED by kobra/emitter_py.py -- do not edit by hand.
Source: DjinnOS_Shyagzun/shygazun/sanctum/charters/tile_renderer.ko

Kobra Seth: all  Scope: all  Lo: all
"""
from __future__ import annotations
import dataclasses


class KobraSuccess:
    """Kobra success carrier (KaelShi)."""
    def __init__(self, value):
        self.value = value
    def __bool__(self) -> bool:
        return True


class KobraError(Exception):
    """Kobra error carrier (KaelKe)."""


def kysha(*branches):
    """Kysha gate: all branches must be non-None."""
    if not all(b is not None for b in branches):
        raise KobraError("kysha gate failed")
    return branches


def kyra(value):
    """Kyra: identity / control token pass-through."""
    return value



# ── Lo: SethTileRenderer::TileRenderer-1-1::LoGaoh ──────────────────

# meta: MavoRendererSpec
renderer_wu_ung = "MavoRendererWuUng"  # WuUng register: TheiaGaoh
gl_tex_wu_ung = "MavoGlTexWuUng"  # WuUng register: TheiaAo
gl_buf_wu_ung = "MavoGlBufWuUng"  # WuUng register: TheiaYe
shader_wu_ung = "MavoShaderWuUng"  # WuUng register: TheiaUi
draw_call_wu_ung = "MavoDrawCallWuUng"  # WuUng register: TheiaShu

# ── Lo: SethTileRenderer::TileRenderer-1-1::LoAo ────────────────────


@dataclasses.dataclass
class RendererDecl:
    tongue_eq: str = ""


@dataclasses.dataclass
class GLTexDecl(RendererDecl):
    tongue_eq: str = "MavoGlTexWuUng"
    width: int = 0
    height: int = 0
    data: bytes = b""
    handle: object = dataclasses.field(default=None, repr=False)


@dataclasses.dataclass
class GLBufferDecl(RendererDecl):
    tongue_eq: str = "MavoGlBufWuUng"
    vbo_data: bytes = b""
    handle: object = dataclasses.field(default=None, repr=False)
    stride: int = 44


_VERT_SRC = """
#version 330 core
layout(location=0) in vec3 a_pos;
layout(location=1) in vec3 a_normal;
layout(location=2) in vec2 a_uv;
uniform mat4 u_mvp;
out vec2 v_uv;
void main() { gl_Position = u_mvp * vec4(a_pos, 1.0); v_uv = a_uv; }
"""

_FRAG_SRC = """
#version 330 core
uniform sampler2D u_atlas;
in vec2 v_uv;
out vec4 frag_color;
void main() { frag_color = texture(u_atlas, v_uv); }
"""

@dataclasses.dataclass
class ShaderDecl(RendererDecl):
    tongue_eq: str = "MavoShaderWuUng"
    vertex_src: str = dataclasses.field(default_factory=lambda: _VERT_SRC)
    fragment_src: str = dataclasses.field(default_factory=lambda: _FRAG_SRC)
    program: object = dataclasses.field(default=None, repr=False)


@dataclasses.dataclass
class DrawCallDecl(RendererDecl):
    tongue_eq: str = "MavoDrawCallWuUng"
    index_data: list = dataclasses.field(default_factory=list)
    uniforms: dict = dataclasses.field(default_factory=dict)
    tex_slot: str = ""
    vertex_count: int = 0


def renderer_read_eval(tex, buf, shader, draw_calls):
    if not isinstance(tex, GLTexDecl):
        raise KobraError(f"renderer_read_eval: expected GLTexDecl, got {type(tex)}")
    if not isinstance(buf, GLBufferDecl):
        raise KobraError(f"renderer_read_eval: expected GLBufferDecl, got {type(buf)}")
    if not isinstance(shader, ShaderDecl):
        raise KobraError(f"renderer_read_eval: expected ShaderDecl, got {type(shader)}")
    for c in (draw_calls if hasattr(draw_calls, "__iter__") else [draw_calls]):
        if not isinstance(c, DrawCallDecl):
            raise KobraError(f"renderer_read_eval: invalid DrawCallDecl: {c}")
    return True


def renderer_index_el(call, read_eval=None):
    return call


# ── Lo: SethTileRenderer::TileRenderer-1-1::LoYe ────────────────────


def shader_compile_eval(shader, ctx):
    if ctx is None:
        shader.program = "headless"
        return shader
    try:
        shader.program = ctx.program(
            vertex_shader=shader.vertex_src,
            fragment_shader=shader.fragment_src,
        )
    except Exception as e:
        raise KobraError(f"shader_compile_eval: GL compile failed: {e}") from e
    return shader


def shader_el(shader, ctx=None):
    return shader_compile_eval(shader, ctx)


# ── Lo: SethTileRenderer::TileRenderer-1-1::LoUi ────────────────────


def tex_upload_eval(tex, ctx, ocean=None):
    if ctx is None:
        tex.handle = "headless"
        return tex
    if not tex.data:
        raise KobraError("tex_upload_eval: no pixel data")
    try:
        tex.handle = ctx.texture((tex.width, tex.height), 4, tex.data)
    except Exception as e:
        raise KobraError(f"tex_upload_eval: GL upload failed: {e}") from e
    return tex


def tex_upload_el(tex, ctx=None):
    return tex_upload_eval(tex, ctx)


def buf_upload_eval(buf, ctx, gyges=None):
    if ctx is None:
        buf.handle = "headless"
        return buf
    if not buf.vbo_data:
        raise KobraError("buf_upload_eval: no VBO data")
    try:
        buf.handle = ctx.buffer(buf.vbo_data)
    except Exception as e:
        raise KobraError(f"buf_upload_eval: GL upload failed: {e}") from e
    return buf


def buf_upload_el(buf, ctx=None):
    return buf_upload_eval(buf, ctx)


# ── Lo: SethTileRenderer::TileRenderer-1-1::LoShu ───────────────────


def draw_call_eval(call, tex, buf, shader):
    if not isinstance(call, DrawCallDecl):
        raise KobraError("draw_call_eval: expected DrawCallDecl")
    call.vertex_count = len(call.index_data)
    call.uniforms["u_atlas"] = 0
    return {
        "index_count": len(call.index_data),
        "index_data":  call.index_data,
        "tex_handle":  getattr(tex,    "handle",  None),
        "buf_handle":  getattr(buf,    "handle",  None),
        "shader":      getattr(shader, "program", None),
        "uniforms":    dict(call.uniforms),
    }


def draw_call_el(call, tex=None, buf=None, shader=None):
    if tex is not None and buf is not None and shader is not None:
        draw_call_eval(call, tex, buf, shader)
    return call


# ── Lo: SethTileRenderer::TileRenderer-1-1::LoLao ───────────────────


def frame_render_eval(ctx, ocean, gyges, shader):
    if isinstance(ocean, dict):
        w, h       = ocean.get("width", 0), ocean.get("height", 0)
        atlas_data = bytes(ocean.get("data", b""))
    else:
        w = h = 0
        atlas_data = bytes(ocean) if ocean else b""
    if isinstance(gyges, dict):
        vbo_data = bytes(gyges.get("vbo", b""))
    else:
        vbo_data = bytes(gyges) if gyges else b""
    vertex_count = len(vbo_data) // 44
    tex    = tex_upload_eval(GLTexDecl(width=w, height=h, data=atlas_data), ctx)
    buf    = buf_upload_eval(GLBufferDecl(vbo_data=vbo_data), ctx)
    s      = shader if isinstance(shader, ShaderDecl) else ShaderDecl()
    s      = shader_compile_eval(s, ctx)
    call   = DrawCallDecl(index_data=list(range(vertex_count)))
    desc   = draw_call_eval(call, tex, buf, s)
    return {
        "tex_handle":   desc["tex_handle"],
        "buf_handle":   desc["buf_handle"],
        "shader":       desc["shader"],
        "vertex_count": vertex_count,
        "headless":     (ctx is None),
    }


def renderer_shi_wu_ung(frame, draw_call=None):
    return KobraSuccess(frame)


def renderer_ke_wu_ung(msg="renderer error"):
    raise KobraError(msg)


def renderer_ep_em(ctx, ocean, gyges, shader=None):
    try:
        result = frame_render_eval(ctx, ocean, gyges, shader or ShaderDecl())
        return renderer_shi_wu_ung(result).value
    except KobraError:
        raise
    except Exception as e:
        renderer_ke_wu_ung(str(e))

