"""
Void Wraiths
============
Peri-primordial. Not derived from corruption.
Generated by *noticed* absence — unnoticed absence produces nothing.
Bound only by the conceptual presence of absence.

The three Void Wraiths: Negaya (2003_VDWR), Vios (2002_VDWR), Haldoro (2001_VDWR).

They observe three things for the Orrery:
  1. Who the player kills             — lives made absent
  2. What the player doesn't say      — words absent from dialogue when speech was available
  3. What the player doesn't do ON PURPOSE — intentional omissions with repetition
     (single absence = noise; pattern = signal; wraith appears when absence becomes practice)

Mechanically:
  - Track opportunity counts per action type per player
  - When (opportunities - taken) >= threshold AND opportunities >= min_repetitions,
    an observation fires
  - Wraiths don't announce themselves
  - The player may not know they exist until they see the Orrery

Each wraith has a domain of observation, a coil layer resonance, and a
minimum repetition threshold.

Connection to Ko flags:
  - "absence_practiced" KoFlag is raised by Vios when omission patterns are strong
  - "grief_without_dissolution" has Void Wraith resonance (Negaya witnesses grief work)
  - "recognition_mutual" draws Haldoro's attention (recognition is presence-work)

Connection to dream calibration:
  - Void Wraiths can read the dreaming faces of layers (9–16) — Rose tongue
  - Dream entries in the journal always trigger a Void Wraith observation (Negaya)
  - The 24-layer density changes when a Void Wraith observes a significant pattern
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, Optional


class ObservationKind(str, Enum):
    LIFE_MADE_ABSENT    = "life.made_absent"      # Haldoro — kills, letting die
    WORD_WITHHELD       = "word.withheld"          # Vios — speech not taken
    OMISSION_PATTERN    = "omission.pattern"       # Vios — repeated intentional absence
    DREAM_ENTRY         = "journal.dream.written"  # Negaya — watches what Hypatia writes in dream
    ENCOUNTER_SKIPPED   = "encounter.skipped"      # Vios — deliberate non-engagement
    QUEST_ABANDONED     = "quest.abandoned"        # Haldoro — commitments unmade


@dataclass(frozen=True)
class VoidWraith:
    id:               str              # e.g. "2001_VDWR"
    name:             str
    domain:           str              # what they watch
    observation_kinds: tuple[ObservationKind, ...]
    coil_resonance:   int              # which coil layer (1–12) they primarily read
    min_repetitions:  int              # how many times before a pattern fires
    threshold_ratio:  float           # (missed / opportunities) ratio to trigger
    ko_flag_id:       Optional[str]   # KoFlag raised when threshold crossed
    layer_face:       str             # "waking" | "dreaming" | "both"


VOID_WRAITHS: tuple[VoidWraith, ...] = (
    VoidWraith(
        id="2001_VDWR",
        name="Haldoro",
        domain="Silence — words absent from dialogue when speech was available; Knower of Minds",
        observation_kinds=(
            ObservationKind.WORD_WITHHELD,
        ),
        coil_resonance=10,    # Ne-Soa — names and what goes unspoken
        min_repetitions=3,    # pattern of silence before Haldoro fires
        threshold_ratio=0.5,  # 50% of speech opportunities withheld
        ko_flag_id=None,
        layer_face="dreaming",  # minds are read in the dreaming face
    ),
    VoidWraith(
        id="2002_VDWR",
        name="Vios",
        domain="Omission — what the player doesn't do on purpose, patterns of not-doing; Knower of Souls",
        observation_kinds=(
            ObservationKind.OMISSION_PATTERN,
            ObservationKind.ENCOUNTER_SKIPPED,
            ObservationKind.QUEST_ABANDONED,
        ),
        coil_resonance=9,     # Dyf-Vr — emergent pattern (soul = the pattern of choices)
        min_repetitions=3,    # single absence = noise; pattern = signal
        threshold_ratio=0.6,  # 60% of opportunities missed before Vios fires
        ko_flag_id="absence_practiced",
        layer_face="dreaming",
    ),
    VoidWraith(
        id="2003_VDWR",
        name="Negaya",
        domain="Kill — lives made absent; Knower of Bodies. Also observes dream entries as pattern-site.",
        observation_kinds=(
            ObservationKind.LIFE_MADE_ABSENT,
            ObservationKind.DREAM_ENTRY,    # Negaya is the site of pattern; dream entries are patterned absence-work
        ),
        coil_resonance=6,     # Shak-Lo — entity/identity threshold (body = entity made absent)
        min_repetitions=1,    # every kill and every dream entry is observed
        threshold_ratio=0.0,  # always fires
        ko_flag_id=None,
        layer_face="both",
    ),
)

WRAITH_BY_ID: dict[str, VoidWraith] = {w.id: w for w in VOID_WRAITHS}
WRAITH_BY_NAME: dict[str, VoidWraith] = {w.name: w for w in VOID_WRAITHS}


# ── Observer — tracks per-player opportunity counts and fires observations ────

class WraithObserver:
    """
    Tracks opportunity counts and fires Void Wraith observations via OrreryClient.

    One WraithObserver per player per session.
    Opportunity tracking:
      - Each time an action is available, call `opportunity(action_key)`.
      - Each time the player takes it, call `taken(action_key)`.
      - When the pattern threshold is crossed, an observation fires.

    Parameters
    ----------
    actor_id:
        Player identifier.
    orrery:
        OrreryClient — observations are fired here.
    """

    def __init__(self, actor_id: str, orrery: Any) -> None:
        self._actor_id   = actor_id
        self._orrery     = orrery
        self._opps:  dict[str, int] = {}
        self._taken: dict[str, int] = {}
        self._fired: set[str]       = set()   # observation keys already fired this session

    def opportunity(self, action_key: str) -> None:
        self._opps[action_key] = self._opps.get(action_key, 0) + 1

    def taken(self, action_key: str) -> None:
        self._taken[action_key] = self._taken.get(action_key, 0) + 1

    def life_made_absent(self, target_id: str, context: dict[str, Any] | None = None) -> None:
        """Negaya (Knower of Bodies) always observes a life made absent."""
        self._orrery.void_wraith_observe(ObservationKind.LIFE_MADE_ABSENT, {
            "actor_id": self._actor_id,
            "target_id": target_id,
            "wraith": "Negaya",
            **(context or {}),
        })

    def check_omission_pattern(self, action_key: str, kind: ObservationKind = ObservationKind.OMISSION_PATTERN) -> None:
        """
        Check whether the omission pattern for `action_key` crosses Vios's threshold.
        If so, fire an observation (once per session per action_key).
        """
        vios = WRAITH_BY_NAME["Vios"]
        opps  = self._opps.get(action_key, 0)
        taken = self._taken.get(action_key, 0)
        missed = opps - taken

        if opps < vios.min_repetitions:
            return
        if opps == 0:
            return
        ratio = missed / opps
        fire_key = f"vios.{action_key}"
        if ratio >= vios.threshold_ratio and fire_key not in self._fired:
            self._fired.add(fire_key)
            self._orrery.void_wraith_observe(kind, {
                "actor_id": self._actor_id,
                "action_key": action_key,
                "opportunities": opps,
                "taken": taken,
                "missed": missed,
                "ratio": round(ratio, 3),
                "wraith": "Vios",
            })

    def dream_entry_observed(self, entry_id: str, title: str) -> None:
        """Negaya observes every dream journal entry."""
        self._orrery.void_wraith_observe(ObservationKind.DREAM_ENTRY, {
            "actor_id": self._actor_id,
            "entry_id": entry_id,
            "title": title,
            "wraith": "Negaya",
        })

    def snapshot(self) -> dict[str, Any]:
        return {
            "actor_id":  self._actor_id,
            "opportunities": dict(self._opps),
            "taken":         dict(self._taken),
            "fired_this_session": list(self._fired),
        }
